name = "LegendMakie"
uuid = "ce9a434a-d062-4f11-9371-3059ddb1c48a"
version = "0.1.0"

[deps]
MakieCore = "20f20a25-4f0e-4fdf-b5d1-57303727442b"

[weakdeps]
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MathTeXEngine = "0a4f8689-d25c-4efe-a92b-7142dfc1aa53"
RadiationDetectorSignals = "bf2c0563-65cf-5db2-a620-ceb7de82658c"

[extensions]
LegendMakieExt = ["Makie", "LaTeXStrings", "MathTeXEngine"]
LegendMakieRadiationDetectorSignalsExt = "RadiationDetectorSignals"

[compat]
LaTeXStrings = "1.2"
Makie = "0.22"
MakieCore = "0.9"
MathTeXEngine = "0.6.1"
RadiationDetectorSignals = "0.3.8"
julia = "1.10"
