name = "LegendMakie"
uuid = "ce9a434a-d062-4f11-9371-3059ddb1c48a"
version = "0.1.0"

[deps]
MakieCore = "20f20a25-4f0e-4fdf-b5d1-57303727442b"

[weakdeps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MathTeXEngine = "0a4f8689-d25c-4efe-a92b-7142dfc1aa53"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
RadiationDetectorSignals = "bf2c0563-65cf-5db2-a620-ceb7de82658c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[extensions]
LegendMakieExt = ["Makie", "Dates", "FileIO", "Format", "LaTeXStrings", "MathTeXEngine", "StatsBase", "Unitful"]
LegendMakieMeasurementsExt = ["Makie", "LaTeXStrings", "Measurements"]
LegendMakieRadiationDetectorSignalsExt = "RadiationDetectorSignals"

[compat]
Dates = "1"
FileIO = "1"
Format = "1"
LaTeXStrings = "1.2"
Makie = "0.22"
MakieCore = "0.9"
MathTeXEngine = "0.6.1"
Measurements = "2.5"
RadiationDetectorSignals = "0.3.8"
StatsBase = "0.33.7, 0.34"
Unitful = "1.6"
julia = "1.10"
